#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

n=0
while ((n < 10))
do
	((n++))
	if ((n == 4))
	then
		echo "bad luck"
		continue
	elif ((n == 8))
	then
		echo "good luck"
		continue
	else
	echo "Best School"
	fi
done

